"""Service helpers for Oh Myself."""

from ohmyself.services.session_storage import get_project_session_dir, load_latest_session_snapshot, save_session_snapshot
from ohmyself.services.transcript_memory import SessionTranscriptWriter
from ohmyself.services.user_profile import generate_user_profile, get_user_profile_path, load_user_profile, save_user_profile
from ohmyself.services.experience import (
    append_experience,
    build_experience_answer_prompt,
    build_experience_organize_prompt,
    build_experience_retrieval_task,
    get_default_experience_path,
    get_experience_dir,
    has_experience_content,
)
from ohmyself.services.plan import (
    append_plan,
    build_plan_organize_prompt,
    get_plan_inbox_path,
    get_plan_dir,
    get_plan_path,
    has_plan_content,
    has_plan_inbox_content,
    parse_plan_content,
    read_plan_inbox,
    read_today_plan,
)
from ohmyself.services.goal import (
    MAX_ACTIVE_GOALS,
    GoalError,
    GoalLimitError,
    GoalNotFoundError,
    append_goal,
    complete_goal,
    format_goals_markdown,
    get_goal_dir,
    get_goal_path,
    has_goal_content,
    list_goals,
    stop_goal,
    update_goal_progress,
)

__all__ = [
    "SessionTranscriptWriter",
    "MAX_ACTIVE_GOALS",
    "GoalError",
    "GoalLimitError",
    "GoalNotFoundError",
    "append_experience",
    "append_goal",
    "append_plan",
    "build_experience_answer_prompt",
    "build_experience_organize_prompt",
    "build_experience_retrieval_task",
    "build_plan_organize_prompt",
    "get_plan_inbox_path",
    "generate_user_profile",
    "get_default_experience_path",
    "get_experience_dir",
    "get_goal_dir",
    "get_goal_path",
    "get_plan_dir",
    "get_plan_path",
    "get_project_session_dir",
    "has_experience_content",
    "has_goal_content",
    "has_plan_content",
    "has_plan_inbox_content",
    "get_user_profile_path",
    "load_latest_session_snapshot",
    "load_user_profile",
    "list_goals",
    "parse_plan_content",
    "read_plan_inbox",
    "read_today_plan",
    "save_user_profile",
    "save_session_snapshot",
    "complete_goal",
    "format_goals_markdown",
    "stop_goal",
    "update_goal_progress",
]
