"""Service helpers for Oh Myself."""

from ohmyself.services.session_storage import get_project_session_dir, load_latest_session_snapshot, save_session_snapshot
from ohmyself.services.transcript_memory import SessionTranscriptWriter
from ohmyself.services.user_profile import generate_user_profile, get_user_profile_path, load_user_profile, save_user_profile
from ohmyself.services.experience import (
    append_experience,
    build_experience_answer_prompt,
    build_experience_organize_prompt,
    build_experience_retrieval_task,
    get_default_experience_path,
    get_experience_dir,
    has_experience_content,
)
from ohmyself.services.plan import (
    append_plan,
    build_plan_organize_prompt,
    get_plan_inbox_path,
    get_plan_dir,
    get_plan_path,
    has_plan_content,
    has_plan_inbox_content,
    parse_plan_content,
    read_plan_inbox,
    read_today_plan,
)
from ohmyself.services.goal import (
    MAX_ACTIVE_GOALS,
    GoalError,
    GoalLimitError,
    GoalNotFoundError,
    append_goal,
    complete_goal,
    ensure_goal_dir,
    format_goals_markdown,
    get_goal_dir,
    get_goal_path,
    has_goal_content,
    list_goals,
    stop_goal,
    update_goal_progress,
)
from ohmyself.services.goal_agent import GoalAgentContext
from ohmyself.services.goal_memory import (
    AI_NOTES_FILENAME,
    CONTEXT_FILENAME,
    USER_PREFS_FILENAME,
    append_goal_memory,
    ensure_goal_memory_dirs,
    format_goal_memory_for_prompt,
    get_goal_experience_dir,
    get_goal_memory_dir,
    read_goal_memory,
    update_goal_memory_via_ai,
)
from ohmyself.services.goal_memory_retriever import build_goal_memory_retrieval_task
from ohmyself.services.goal_progress import (
    assess_daily_goal_progress,
    get_daily_marker_path,
    get_last_progress_check_date,
    set_last_progress_check_date,
)
from ohmyself.services.goal_session import (
    list_goal_sessions,
    link_session_to_goal,
)

__all__ = [
    "AI_NOTES_FILENAME",
    "CONTEXT_FILENAME",
    "GoalAgentContext",
    "GoalError",
    "GoalLimitError",
    "GoalNotFoundError",
    "MAX_ACTIVE_GOALS",
    "assess_daily_goal_progress",
    "get_daily_marker_path",
    "get_last_progress_check_date",
    "set_last_progress_check_date",
    "SessionTranscriptWriter",
    "USER_PREFS_FILENAME",
    "append_experience",
    "append_goal",
    "append_goal_memory",
    "append_plan",
    "build_experience_answer_prompt",
    "build_experience_organize_prompt",
    "build_experience_retrieval_task",
    "build_plan_organize_prompt",
    "complete_goal",
    "ensure_goal_dir",
    "ensure_goal_memory_dirs",
    "format_goal_memory_for_prompt",
    "format_goals_markdown",
    "generate_user_profile",
    "get_default_experience_path",
    "get_experience_dir",
    "get_goal_dir",
    "get_goal_experience_dir",
    "get_goal_memory_dir",
    "get_goal_path",
    "get_plan_dir",
    "get_plan_inbox_path",
    "get_plan_path",
    "get_project_session_dir",
    "get_user_profile_path",
    "has_experience_content",
    "has_goal_content",
    "has_plan_content",
    "has_plan_inbox_content",
    "link_session_to_goal",
    "list_goal_sessions",
    "list_goals",
    "load_latest_session_snapshot",
    "load_user_profile",
    "parse_plan_content",
    "read_goal_memory",
    "read_plan_inbox",
    "read_today_plan",
    "save_session_snapshot",
    "save_user_profile",
    "stop_goal",
    "update_goal_progress",
    "update_goal_memory_via_ai",
    "build_goal_memory_retrieval_task",
]
